package com.ojodev.cookinghero.recipes.domain.model;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Measure with multiple languages associated.
 *
 */
@ToString
@EqualsAndHashCode
@Getter
public class MeasureMultiLanguageBO {

    private String id; // Generated by name.language = default

    private List<DescriptiveNameBO> names;  // Mandatory

    private MeasureMultiLanguageBO(Builder builder) {
        this.id = builder.getId();
        this.names = builder.names;
    }


    public static class Builder extends IdentifiableBO{

       private List<DescriptiveNameBO> names;

        private LanguageEnumBO defaultLanguage;

        public Builder(List<DescriptiveNameBO> names, LanguageEnumBO defaultLanguage ) {
            super("");
            this.defaultLanguage = defaultLanguage;
            this.names = new ArrayList<>();
            this.names(names);
        }

        public Builder name(DescriptiveNameBO newName) {
            validateName(newName);
            if (languageExists(newName)) {
                replaceName(newName);
            } else {
                addName(newName);
            }
            if (languageIsDefault(newName)) {
                setId(newName.getSingular());
            }
            return this;
        }

        private boolean languageExists(DescriptiveNameBO newName) {
            return this.names.stream().filter(n ->  n.getLanguage() == newName.getLanguage()).findAny().isPresent();
        }

        private Builder replaceName(DescriptiveNameBO newName) {
            this.names.stream().filter(n -> n.getLanguage() == newName.getLanguage()).forEach(n ->
            {
                n.setSingular(newName.getSingular());
                n.setPlural(newName.getPlural());
            });
            return this;
        }

        private Builder addName(DescriptiveNameBO newName) {
            this.names.add(newName);
            return this;
        }

        private boolean languageIsDefault(DescriptiveNameBO newName) {
            return defaultLanguage != null && defaultLanguage == (newName.getLanguage());
        }


        public Builder names(List<DescriptiveNameBO> names) {
            names.stream().forEach(n -> name(n));
            return this;
        }

        public MeasureMultiLanguageBO build() {
            MeasureMultiLanguageBO measureMultiLanguageBO = new MeasureMultiLanguageBO(this);
            validateMeasureObject(measureMultiLanguageBO);
            return measureMultiLanguageBO;
        }

        private void validateName(DescriptiveNameBO name) {
            if (name == null || StringUtils.isEmpty(name.getSingular()) || StringUtils.isEmpty(name.getPlural())) {
                throw new IllegalArgumentException("Names needs to include singular and plural fields");
            }
        }


        private void validateMeasureObject(MeasureMultiLanguageBO measureMultiLanguageBO) {
            if (measureMultiLanguageBO.getNames() == null || measureMultiLanguageBO.getNames().size() == 0) {
                throw new IllegalArgumentException("Measure needs to include at least one name and language fields");
            }
            if (measureMultiLanguageBO.getNames().stream().filter(ln -> defaultLanguage.equals(ln.getLanguage())).count() == 0) {
                throw new IllegalArgumentException("Measure needs to include default language name: " + defaultLanguage);
            }
        }


    }

}
